# Generated by Django 5.1.3 on 2024-11-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='age',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programmer',
            name='full_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmer',
            name='nickname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
